[package]
name = "crabgrind"
version = "0.1.12"
license = "MIT"
edition = "2015"
rust-version = "1.1"
description = "Rust bindings to \"Valgrind Client Request\" interface"
keywords = ["valgrind", "massif", "callgrind", "cachegrind", "helgrind"]
categories = ["api-bindings", "development-tools::profiling", "development-tools"]
repository = "https://github.com/2dav/crabgrind"
homepage = "https://github.com/2dav/crabgrind"
documentation = "https://docs.rs/crabgrind"
readme = "README.md"
build = "build.rs"

[build-dependencies]
cc = { version = "1.0", features = ['parallel'] }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = []
