version = "Two"
use_small_heuristics = "Max"
merge_derives = false

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true
comment_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true
